fix(angular-virtual): fix proxying of computed functions with args
Calls to 'getOffsetForAlignment', getOffsetForIndex', 'getVirtualItemForOffset', and 'indexFromElement' now work as expected instead of erroring with `TypeError: fn is not a function`.